### ISSUE TITLE
Upgrade pg version to 8 for compatibility with newer Postgresql versions

### ISSUE THREAD

**Issue by adorsk** [lukechilds/keyv-postgres#33]
Hello, thank you for making the keyv library.

`kevy-postgres` is currently using v7 of the `pg` library. However, this seems to not work with more recent versions of postgresql (?) For example, postgresql 12.

Unfortunately I can't investigate further at the moment. But if others have issues w/ using keyv with postgresql out-of-the-box, it may be because of the older `pg` version.

**Comment by Stefouch** [comment]
Hi!

I'm supporting this too update too.

KeyvPostgreSQL does not work under Node >= 14.x

See:
- https://github.com/lukechilds/keyv-sql/issues/28
- https://github.com/brianc/node-postgres/issues/2180 (fixed in `pg@8.0.3`)

**Comment by qharscoet** [comment]
Bump,

Wanted to use keyv for a discord bot and Promises won't resolve when switch from a testing sqlite to postgres :(

**Comment by Stefouch** [comment]
[Discord.JS](https://discord.js.org/#/docs/main/master/general/welcome) is releasing a new version 13, which requires Node v16+

Bots using Keyv's Postgresql can't make the update or they'll break due to this issue.

I would really see it fixed as I don't want to revamp my database system.

*PS: Keyv is suggested in the [Discord.JS Guide](https://discordjs.guide/keyv/)*

**Comment by eightyfive** [comment]
There seem to have a lot of problems with latest versions.

In my case the table `keyv` is never created.

The [`query` that creates the default table](https://github.com/lukechilds/keyv-sql/blob/master/src/index.js#L35) is never fullfilled.

```
$  node -v
v16.1.0

$ psql --version
psql (PostgreSQL) 13.3
```

I'm switching to pure `postgres` for now. Lost a fair amount of time, I hope this will save someone some headaches.
